sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aparna/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aparna/docker-react npm run test
       

